### ISSUE TITLE
klint fails if v2alpha1.CronJob is not enabled on cluster

### ISSUE THREAD

**Issue by wawastein** [uswitch/klint#4]
Hello, it's me again.

So I've built image myself based on ubuntu (your scratch-based version and my alpine-based refused to work for some mysterious reason, claiming that executable couldn't be found, while it was right there in working dir and referenced directly in CMD).

I've launched it in k8s kube-system namespace, took a namespace with problematic pod, which restarts repeatedly, annotated it with:

```
com.uswitch.alert/slack: kube-monitoring
```
Created bot, passed token to klint via secret, and nothing happens.

In logs I see this over and over again:

```ERROR: logging before flag.Parse: E0906 10:55:39.524069       1 reflector.go:199] github.com/uswitch/klint/engine/engine.go:95: Failed to list *v2alpha1.CronJob: the server could not find the requested resource```

As far as I understand, this fails when engine tries to attach rules to resources and nothing gets processed as a result.

We use GKE, and moving to alpha clusters is not what we want to do. Is there a way to disable rule?

**Comment by wawastein** [comment]
Correction: alerts started to work. Question with cronjob rule still applies.

**Comment by pingles** [comment]
Currently there's no option to configure which rules apply. I agree though- it'd be nice to be able to override which rules apply via a command flag or something.

I'll close this and create a new for that if that sounds good?

**Comment by wawastein** [comment]
@pingles sure

**Comment by wawastein** [comment]
@pingles this also produces a lot of logs each time rule is invoked, which is not desired, so I'd throw a sort of `--quiet` key as well
